// Forced/branching continuation prefixes for ghost text (issue #6 follow-up).
//
// Source: LLM-generated (this conversation, 2026-06-22, branch cap lifted
// 2026-06-22) against an explicit rule set, not corpus-mined. A trigger is
// included only if its valid completions are: (a) a function word/"that"/
// "to" closing a *grammatical* frame (not a conventional lexical pairing
// like "make a decision"), and (b) common in IELTS Task 2 academic writing.
// See docs/testing-log.md for why a corpus-mined approach (the original
// 6-entry STREUSLE list) tops out far short of broad coverage: true
// cardinality-1 (single-completion) collocations are rare in natural
// language.
//
// Each entry is [trigger, continuation]. continuation is a single string
// when grammatically forced to one word, or an array of branch strings,
// ordered by LLM-estimated likelihood (most likely first), when more than
// one completion is valid (e.g. "agree" -> [" with", " that", " to", " on"]).
// There is no branch-count cap; the array is as long as there are genuinely
// distinct grammatical completions. The likelihood ordering is an estimate,
// not a measured frequency (no corpus backs it) — ghost.js displays branches
// joined as "first/rest" and Tab-accepts only the first (primary) branch.
//
// Two categories from the original rule set are deliberately excluded:
// verb+gerund-only ("avoid/consider —ing") and concessive-conjunction-form
// ("despite —ing/noun", "although clause"). Both describe a required
// grammatical *form*, not a literal next word, so there is nothing for ghost
// text (which inserts literal text) to suggest. They'd need a separate
// non-insertable "form hint" UI, not this trie.
export const FORCED_CONTINUATIONS = [
  // --- Verb + preposition ---
  ['result', [' in', ' from']],
  ['focus', [' on']],
  ['consist', [' of']],
  ['depend', [' on', ' upon']],
  ['rely', [' on']],
  ['lead', [' to']],
  ['contribute', [' to', ' towards']],
  ['benefit', [' from', ' of']],
  ['suffer', [' from']],
  ['refer', [' to']],
  ['respond', [' to']],
  ['react', [' to']],
  ['differ', [' from', ' in', ' on']],
  ['stem', [' from']],
  ['arise', [' from']],
  ['derive', [' from']],
  ['comply', [' with']],
  ['cope', [' with']],
  ['deal', [' with']],
  ['interfere', [' with']],
  ['participate', [' in']],
  ['engage', [' in']],
  ['specialize', [' in']],
  ['invest', [' in']],
  ['indulge', [' in']],
  ['succeed', [' in']],
  ['struggle', [' with', ' to']],
  ['collaborate', [' with']],
  ['interact', [' with']],
  ['adapt', [' to']],
  ['adjust', [' to']],
  ['belong', [' to']],
  ['amount', [' to', ' of']],
  ['relate', [' to']],
  ['correspond', [' to']],
  ['object', [' to']],
  ['consent', [' to']],
  ['account', [' for']],
  ['compensate', [' for']],
  ['substitute', [' for']],
  ['qualify', [' for']],
  ['insist', [' on', ' that']],
  ['concentrate', [' on']],
  ['elaborate', [' on']],
  ['capitalize', [' on']],
  ['embark', [' on']],
  ['consult', [' with']],
  ['sympathize', [' with']],
  ['associate', [' with']],
  ['combine', [' with']],
  ['originate', [' from']],
  ['emerge', [' from']],
  ['recover', [' from']],
  ['refrain', [' from']],
  ['abstain', [' from']],

  // --- Adjective + preposition ---
  ['interested', [' in']],
  ['responsible', [' for']],
  ['aware', [' of']],
  ['capable', [' of']],
  ['proud', [' of']],
  ['afraid', [' of']],
  ['fond', [' of']],
  ['typical', [' of']],
  ['characteristic', [' of']],
  ['indicative', [' of']],
  ['representative', [' of']],
  ['suspicious', [' of']],
  ['critical', [' of']],
  ['tolerant', [' of']],
  ['independent', [' of']],
  ['devoid', [' of']],
  ['similar', [' to']],
  ['identical', [' to']],
  ['relevant', [' to']],
  ['related', [' to']],
  ['prone', [' to']],
  ['susceptible', [' to']],
  ['resistant', [' to']],
  ['accustomed', [' to']],
  ['subject', [' to']],
  ['sensitive', [' to']],
  ['beneficial', [' to']],
  ['harmful', [' to']],
  ['crucial', [' to']],
  ['vital', [' to']],
  ['detrimental', [' to']],
  ['inferior', [' to']],
  ['superior', [' to']],
  ['familiar', [' with']],
  ['satisfied', [' with']],
  ['concerned', [' with', ' about']],
  ['consistent', [' with']],
  ['compatible', [' with']],
  ['associated', [' with']],
  ['involved', [' in']],
  ['skilled', [' in']],
  ['proficient', [' in']],
  ['successful', [' in']],
  ['dependent', [' on']],
  ['reliant', [' on']],
  ['based', [' on']],
  ['keen', [' on', ' to']],
  ['worried', [' about']],
  ['anxious', [' about', ' to']],
  ['curious', [' about']],
  ['optimistic', [' about']],
  ['pessimistic', [' about']],

  // --- Noun + preposition ---
  ['impact', [' on']],
  ['effect', [' on']],
  ['influence', [' on']],
  ['emphasis', [' on']],
  ['reliance', [' on']],
  ['access', [' to']],
  ['solution', [' to', ' for']],
  ['answer', [' to']],
  ['key', [' to']],
  ['approach', [' to']],
  ['attitude', [' to']],
  ['reaction', [' to']],
  ['contribution', [' to']],
  ['addition', [' to']],
  ['alternative', [' to']],
  ['exception', [' to']],
  ['threat', [' to']],
  ['demand', [' for', ' that']],
  ['need', [' for', ' to']],
  ['reason', [' for']],
  ['basis', [' for']],
  ['grounds', [' for']],
  ['respect', [' for']],
  ['lack', [' of']],
  ['variety', [' of']],
  ['proportion', [' of']],
  ['percentage', [' of']],
  ['shortage', [' of']],
  ['absence', [' of']],
  ['presence', [' of']],
  ['awareness', [' of']],
  ['knowledge', [' of']],
  ['definition', [' of']],
  ['significance', [' of']],
  ['evidence', [' of']],
  ['proof', [' of']],
  ['member', [' of']],

  // --- Reporting verb + "that" ---
  ['argue', [' that']],
  ['suggest', [' that']],
  ['claim', [' that', ' to']],
  ['believe', [' that']],
  ['demonstrate', [' that']],
  ['indicate', [' that']],
  ['reveal', [' that']],
  ['imply', [' that']],
  ['conclude', [' that']],
  ['acknowledge', [' that']],
  ['assert', [' that']],
  ['maintain', [' that']],
  ['contend', [' that']],
  ['emphasize', [' that']],
  ['recognize', [' that']],
  ['state', [' that']],
  ['confirm', [' that']],
  ['establish', [' that']],
  ['illustrate', [' that']],

  // --- Appositive noun + "that" ---
  ['the fact', [' that']],
  ['the view', [' that']],
  ['the idea', [' that']],
  ['the belief', [' that']],
  ['the notion', [' that']],
  ['the assumption', [' that']],
  ['the claim', [' that']],
  ['the argument', [' that']],
  ['the possibility', [' that']],
  ['the likelihood', [' that']],
  ['the suggestion', [' that']],
  ['the concern', [' that']],
  ['the hope', [' that']],
  ['the assertion', [' that']],

  // --- Quantifier + "of" ---
  ['a number', [' of']],
  ['the majority', [' of']],
  ['a range', [' of']],
  ['a wide range', [' of']],
  ['a variety', [' of']],
  ['a proportion', [' of']],
  ['a minority', [' of']],
  ['a great deal', [' of']],
  ['a large number', [' of']],
  ['a small number', [' of']],
  ['plenty', [' of']],
  ['a lack', [' of']],
  ['a host', [' of']],
  ['a multitude', [' of']],
  ['a series', [' of']],
  ['the bulk', [' of']],
  ['a handful', [' of']],

  // --- Fixed prepositional phrases ---
  ['as soon', ' as'],
  ['in front', ' of'],
  ['in the middle', ' of'],
  ['according', ' to'],
  ['in need', ' of'],
  ['when it comes', ' to'],
  ['in terms', [' of']],
  ['in addition', [' to']],
  ['in spite', [' of']],
  ['in case', [' of']],
  ['on behalf', [' of']],
  ['in light', [' of']],
  ['with regard', [' to']],
  ['in relation', [' to']],
  ['in response', [' to']],
  ['in contrast', [' to']],
  ['as opposed', [' to']],
  ['prior', [' to']],
  ['due', [' to']],
  ['owing', [' to']],
  ['contrary', [' to']],
  ['in accordance', [' with']],
  ['in conjunction', [' with']],
  ['in line', [' with']],
  ['together', [' with']],
  ['along', [' with']],
  ['as well', [' as']],
  ['rather', [' than']],
  ['apart', [' from']],
  ['aside', [' from']],
  ['regardless', [' of']],
  ['on top', [' of']],
  ['in favor', [' of']],
  ['in the absence', [' of']],
  ['in the event', [' of']],
  ['for the sake', [' of']],
  ['on the basis', [' of']],
  ['at the expense', [' of']],

  // --- Verb + infinitive only ---
  ['tend', [' to']],
  ['aim', [' to', ' for']],
  ['seek', [' to']],
  ['fail', [' to']],
  ['manage', [' to']],
  ['attempt', [' to']],
  ['intend', [' to']],
  ['plan', [' to', ' for']],
  ['decide', [' to']],
  ['hope', [' to']],
  ['strive', [' to', ' for']],
  ['endeavor', [' to']],
  ['proceed', [' to']],
  ['choose', [' to']],
  ['refuse', [' to']],
  ['afford', [' to']],
  ['deserve', [' to']],
  ['appear', [' to']],
  ['seem', [' to']],

  // --- Adjective in it-construction ("it is [adjective] ___") ---
  ['important', [' to', ' that']],
  ['necessary', [' to', ' that']],
  ['essential', [' to', ' that']],
  ['possible', [' to', ' that']],
  ['difficult', [' to']],
  ['easy', [' to']],
  ['hard', [' to']],
  ['clear', [' that', ' of']],
  ['obvious', [' that']],
  ['true', [' that', ' to']],
  ['likely', [' that']],
  ['evident', [' that']],
  ['apparent', [' that']],
  ['unlikely', [' that']],
  ['arguable', [' that']],

  // --- Additional verb/noun + preposition, branch cap lifted 2026-06-22 ---
  ['agree', [' with', ' that', ' to', ' on']],
  ['vary', [' in', ' with', ' from', ' by']],
  ['compare', [' to', ' with']],
  ['comparison', [' with', ' to', ' between']],
  ['think', [' that', ' of', ' about']],
  ['talk', [' about', ' to', ' of', ' into']],
  ['speak', [' about', ' to', ' of']],
  ['write', [' about', ' on']],
  ['look', [' at', ' for', ' into']],
  ['care', [' about', ' for']],
  ['complain', [' about', ' of']],
  ['warn', [' about', ' of', ' that', ' to']],
  ['blame', [' for', ' on']],
  ['apologize', [' for', ' to']],
  ['thank', [' for']],
  ['congratulate', [' on']],
  ['comment', [' on']],
  ['reflect', [' on']],
  ['build', [' on']],
  ['draw', [' on', ' from']],
  ['attribute', [' to']],
  ['ascribe', [' to']],
  ['link', [' to', ' with', ' between']],
  ['connect', [' to', ' with']],
  ['correlate', [' with']],
  ['range', [' from', ' between']],
  ['compete', [' with', ' for', ' against']],
  ['communicate', [' with']],
  ['cooperate', [' with']],
  ['conform', [' to']],
  ['adhere', [' to']],

  // --- Expansion round 2, 2026-06-22: more verb/adjective/noun + preposition ---
  ['rest', [' on', ' upon']],
  ['hinge', [' on']],
  ['center', [' on', ' around']],
  ['revolve', [' around']],
  ['culminate', [' in']],
  ['translate', [' into']],
  ['evolve', [' into', ' from']],
  ['transform', [' into']],
  ['convert', [' into', ' to']],
  ['integrate', [' into', ' with']],
  ['incorporate', [' into']],
  ['exclude', [' from']],
  ['exempt', [' from']],
  ['distinguish', [' between', ' from']],
  ['differentiate', [' between', ' from']],
  ['discriminate', [' against', ' between']],
  ['cater', [' to', ' for']],
  ['appeal', [' to']],
  ['apply', [' to', ' for']],
  ['pertain', [' to']],
  ['attend', [' to']],
  ['cling', [' to']],
  ['aspire', [' to']],
  ['resort', [' to']],
  ['boil down', [' to']],
  ['add', [' to']],
  ['subscribe', [' to']],
  ['commit', [' to']],
  ['devote', [' to']],
  ['dedicate', [' to']],
  ['expose', [' to']],
  ['limit', [' to']],
  ['restrict', [' to']],
  ['confine', [' to']],
  ['credit', [' with', ' for']],
  ['provide', [' with', ' for']],
  ['equip', [' with']],
  ['supply', [' with', ' of']],
  ['coincide', [' with']],
  ['overlap', [' with']],
  ['clash', [' with']],
  ['conflict', [' with', ' between', ' over']],
  ['align', [' with']],
  ['merge', [' with']],
  ['identify', [' with', ' as']],
  ['equate', [' with', ' to']],
  ['negotiate', [' with']],

  ['eligible', [' for']],
  ['liable', [' for', ' to']],
  ['entitled', [' to']],
  ['committed', [' to']],
  ['dedicated', [' to']],
  ['devoted', [' to']],
  ['exposed', [' to']],
  ['attached', [' to']],
  ['opposed', [' to']],
  ['addicted', [' to']],
  ['allergic', [' to']],
  ['immune', [' to', ' from']],
  ['vulnerable', [' to']],
  ['unique', [' to']],
  ['native', [' to']],
  ['equivalent', [' to']],
  ['comparable', [' to', ' with']],
  ['parallel', [' to', ' with']],
  ['analogous', [' to']],
  ['distinct', [' from']],
  ['separate', [' from']],
  ['different', [' from', ' to']],
  ['free', [' from', ' of']],
  ['short', [' of']],
  ['full', [' of']],
  ['rich', [' in']],
  ['poor', [' in']],
  ['deficient', [' in']],
  ['lacking', [' in']],
  ['abundant', [' in']],
  ['weak', [' in']],
  ['strong', [' in']],
  ['experienced', [' in']],
  ['engaged', [' in']],
  ['fluent', [' in']],
  ['qualified', [' for', ' to', ' in']],
  ['suited', [' to', ' for']],
  ['adapted', [' to', ' for']],
  ['geared', [' towards', ' to']],
  ['oriented', [' towards']],
  ['centered', [' on', ' around']],
  ['rooted', [' in']],
  ['grounded', [' in']],
  ['embedded', [' in']],
  ['invested', [' in']],
  ['determined', [' to']],

  ['relationship', [' between', ' with']],
  ['connection', [' between', ' with', ' to']],
  ['gap', [' between']],
  ['balance', [' between']],
  ['distinction', [' between']],
  ['difference', [' between']],
  ['correlation', [' between', ' with']],
  ['interaction', [' between', ' with']],
  ['collaboration', [' between', ' with']],
  ['cooperation', [' between', ' with']],
  ['competition', [' between', ' for', ' with']],
  ['cause', [' of', ' for', ' to']],
  ['source', [' of']],
  ['origin', [' of']],
  ['root', [' of']],
  ['consequence', [' of', ' for']],
  ['implication', [' of', ' for']],
  ['outcome', [' of']],
  ['advantage', [' of', ' over']],
  ['disadvantage', [' of']],
  ['priority', [' over', ' for']],
  ['preference', [' for', ' over']],
  ['tendency', [' to', ' towards']],
  ['inclination', [' to', ' towards']],
  ['willingness', [' to']],
  ['ability', [' to']],
  ['capacity', [' to', ' for']],
  ['opportunity', [' to', ' for']],
  ['chance', [' to', ' of']],
  ['right', [' to']],
  ['freedom', [' to', ' from']],
  ['commitment', [' to']],
  ['obligation', [' to']],
  ['responsibility', [' for', ' to']],
  ['duty', [' to']],
  ['concern', [' about', ' for', ' over']],
  ['insight', [' into']],
  ['perspective', [' on']],
  ['viewpoint', [' on']],
  ['stance', [' on']],
  ['opinion', [' on', ' about', ' of']],
  ['view', [' on', ' of', ' about']],
  ['belief', [' in']],
  ['faith', [' in']],
  ['trust', [' in']],
  ['confidence', [' in']],
  ['doubt', [' that', ' about']],
  ['interest', [' in']],
  ['expertise', [' in']],
  ['experience', [' in', ' of', ' with']],
  ['background', [' in']],
  ['training', [' in']],
  ['degree', [' in', ' of']],
  ['increase', [' in', ' of']],
  ['decrease', [' in']],
  ['decline', [' in', ' to']],
  ['rise', [' in']],
  ['fall', [' in']],
  ['growth', [' in', ' of']],
  ['reduction', [' in', ' of']],
  ['improvement', [' in']],
  ['investment', [' in']],
  ['participation', [' in']],
  ['involvement', [' in']],

  // --- Expansion round 2: reporting verb + "that" ---
  ['note', [' that']],
  ['observe', [' that']],
  ['show', [' that']],
  ['prove', [' that']],
  ['find', [' that']],
  ['discover', [' that']],
  ['realize', [' that']],
  ['understand', [' that']],
  ['assume', [' that']],
  ['predict', [' that']],
  ['propose', [' that']],
  ['recommend', [' that']],
  ['point out', [' that']],

  // --- Expansion round 2: appositive noun + "that" ---
  ['the observation', [' that']],
  ['the conclusion', [' that']],
  ['the finding', [' that']],
  ['the perception', [' that']],
  ['the misconception', [' that']],
  ['the principle', [' that']],
  ['the requirement', [' that']],
  ['the recommendation', [' that']],
  ['the prediction', [' that']],
  ['the risk', [' that']],
  ['the danger', [' that']],
  ['the chance', [' that']],

  // --- Expansion round 2: quantifier + "of" ---
  ['a couple', [' of']],
  ['a portion', [' of']],
  ['a fraction', [' of']],
  ['the rest', [' of']],
  ['a set', [' of']],
  ['a combination', [' of']],
  ['a mixture', [' of']],
  ['a sense', [' of']],
  ['a degree', [' of']],

  // --- Expansion round 2: fixed prepositional phrases ---
  ['with respect', [' to']],
  ['in comparison', [' to', ' with']],
  ['in connection', [' with']],
  ['in proportion', [' to']],
  ['in keeping', [' with']],
  ['in collaboration', [' with']],
  ['in cooperation', [' with']],
  ['in combination', [' with']],
  ['in contact', [' with']],
  ['in touch', [' with']],
  ['in charge', [' of']],
  ['in control', [' of']],
  ['in support', [' of']],
  ['in pursuit', [' of']],
  ['in recognition', [' of']],
  ['in defense', [' of']],
  ['in violation', [' of']],
  ['on account', [' of']],
  ['on the grounds', [' of', ' that']],
  ['for fear', [' of']],
  ['with the aim', [' of']],
  ['with the exception', [' of']],
  ['with the intention', [' of']],
  ['for the purpose', [' of']],
  ['by virtue', [' of']],
  ['by means', [' of']],
  ['by way', [' of']],
  ['in the wake', [' of']],
  ['in the interest', [' of']],
  ['at the cost', [' of']],
  ['at the heart', [' of']],
  ['at the forefront', [' of']],
  ['in the form', [' of']],
  ['as a result', [' of']],
  ['as a consequence', [' of']],

  // --- Expansion round 2: verb + infinitive only ---
  ['long', [' to', ' for']],
  ['wish', [' to']],
  ['expect', [' to']],
  ['want', [' to']],
  ['desire', [' to']],
  ['promise', [' to']],
  ['threaten', [' to']],
  ['pledge', [' to']],
  ['undertake', [' to']],
  ['resolve', [' to']],
  ['prepare', [' to', ' for']],
  ['cease', [' to']],
  ['neglect', [' to']],
  ['hesitate', [' to']],
  ['dare', [' to']],
  ['pretend', [' to']],

  // --- Expansion round 3, 2026-06-22: more verb/noun + preposition ---
  ['yearn', [' for']],
  ['fight', [' for', ' against']],
  ['vote', [' for', ' against', ' on']],
  ['campaign', [' for', ' against']],
  ['advocate', [' for']],
  ['settle', [' for', ' on']],
  ['opt', [' for', ' to']],
  ['wait', [' for']],
  ['ask', [' for', ' about']],
  ['search', [' for']],
  ['owe', [' to']],
  ['yield', [' to']],
  ['succumb', [' to']],
  ['submit', [' to']],
  ['testify', [' to']],
  ['attest', [' to']],
  ['listen', [' to']],
  ['give rise', [' to']],
  ['pay attention', [' to']],
  ['take part', [' in']],
  ['play a role', [' in']],
  ['play a part', [' in']],
  ['keep pace', [' with']],
  ['keep up', [' with']],
  ['catch up', [' with']],
  ['put up', [' with']],
  ['come up', [' with', ' against']],

  ['attention', [' to']],
  ['surplus', [' of']],
  ['scarcity', [' of']],
  ['abundance', [' of']],
  ['wealth', [' of']],
  ['array', [' of']],
  ['spectrum', [' of']],
  ['myriad', [' of']],
  ['plethora', [' of']],
  ['wave', [' of']],
  ['surge', [' in', ' of']],
  ['spike', [' in']],
  ['boost', [' to', ' in']],
  ['drop', [' in']],
  ['shift', [' in', ' towards', ' to']],
  ['transition', [' to', ' from']],
  ['trend', [' towards', ' in']],
  ['barrier', [' to']],
  ['obstacle', [' to']],
  ['hindrance', [' to']],
  ['constraint', [' on']],
  ['restriction', [' on']],
  ['limitation', [' on', ' of']],
  ['ban', [' on', ' from']],
  ['tax', [' on']],
  ['burden', [' on']],
  ['pressure', [' on', ' to', ' into']],
  ['strain', [' on']],
  ['toll', [' on']],
  ['stress', [' on']],
  ['premium', [' on']],
  ['verdict', [' on']],
  ['report', [' on']],
  ['research', [' on', ' into']],
  ['study', [' of', ' on', ' into']],
  ['investigation', [' into']],
  ['inquiry', [' into']],
  ['breakthrough', [' in']],
  ['advance', [' in']],
  ['advancement', [' in']],
  ['progress', [' in', ' towards']],
  ['development', [' in', ' of']],
  ['expansion', [' of', ' in']],
  ['deterioration', [' in', ' of']],
  ['downturn', [' in']],
  ['fluctuation', [' in']],
  ['variation', [' in']],
  ['diversity', [' of', ' in']],
  ['scope', [' of', ' for']],
  ['extent', [' of', ' to']],
  ['level', [' of']],
  ['rate', [' of']],
  ['pace', [' of']],
  ['speed', [' of']],
  ['scale', [' of']],
  ['magnitude', [' of']],
  ['severity', [' of']],
  ['intensity', [' of']],
  ['frequency', [' of']],
  ['duration', [' of']],
  ['length', [' of']],
  ['size', [' of']],
  ['quality', [' of']],
  ['quantity', [' of']],
  ['volume', [' of']],
  ['nature', [' of']],
  ['purpose', [' of']],
  ['function', [' of']],
  ['role', [' of', ' in']],
  ['part', [' of', ' in']],
  ['share', [' of', ' in']],
  ['portion', [' of']],
  ['majority', [' of']],
  ['minority', [' of']],
  ['fraction', [' of']],
  ['number', [' of']],

  // --- Expansion round 4, 2026-06-22: appositives, whether-clauses, more adj/verb + prep ---
  ['the truth', [' that']],
  ['the reality', [' that']],
  ['the impression', [' that']],
  ['the expectation', [' that']],
  ['the warning', [' that']],
  ['the rumor', [' that']],
  ['the allegation', [' that']],
  ['the contention', [' that']],
  ['the realization', [' that']],
  ['the awareness', [' that']],
  ['the knowledge', [' that']],

  ['worth', [' noting', ' mentioning', ' considering']],
  ['noteworthy', [' that']],
  ['debatable', [' whether']],
  ['questionable', [' whether']],
  ['uncertain', [' whether']],
  ['unclear', [' whether']],
  ['unsure', [' whether']],
  ['doubtful', [' whether']],
  ['wonder', [' whether']],
  ['determine', [' whether']],
  ['assess', [' whether']],
  ['evaluate', [' whether']],
  ['examine', [' whether']],
  ['question', [' whether']],

  ['spring', [' from']],
  ['flow', [' from']],
  ['follow', [' from']],

  ['synonymous', [' with']],
  ['incompatible', [' with']],
  ['inconsistent', [' with']],
  ['at odds', [' with']],
  ['interchangeable', [' with']],
  ['preoccupied', [' with']],
  ['obsessed', [' with']],
  ['burdened', [' with']],
  ['equipped', [' with']],
  ['indifferent', [' to']],
  ['oblivious', [' to']],
  ['averse', [' to']],
  ['conducive', [' to']],
  ['receptive', [' to']],
  ['resilient', [' to']],
  ['void', [' of']],
  ['stripped', [' of']],
  ['guilty', [' of']],
  ['innocent', [' of']],
  ['convicted', [' of']],
  ['accused', [' of']],
  ['suspected', [' of']],
  ['incapable', [' of']],
  ['worthy', [' of']],
  ['deserving', [' of']],
  ['reminiscent', [' of']],
  ['symptomatic', [' of']],
  ['illustrative', [' of']],
  ['reflective', [' of']],
  ['made up', [' of']],
  ['composed', [' of']],

  // --- Expansion round 5, 2026-06-22: more verb+that/whether, it-construction, appositives ---
  ['alert', [' to']],
  ['notify', [' of']],
  ['inform', [' of']],
  ['remind', [' of', ' that', ' to']],
  ['convince', [' of', ' that', ' to']],
  ['assure', [' of', ' that']],
  ['guarantee', [' that']],
  ['ensure', [' that']],
  ['verify', [' that']],
  ['fear', [' that']],
  ['regret', [' that']],
  ['deny', [' that']],
  ['admit', [' that']],
  ['concede', [' that']],
  ['imagine', [' that']],
  ['presume', [' that']],
  ['speculate', [' that', ' about']],
  ['estimate', [' that']],
  ['anticipate', [' that']],
  ['protest', [' against', ' about']],
  ['rebel', [' against']],
  ['rebellion', [' against']],
  ['resistance', [' to', ' against']],
  ['opposition', [' to']],
  ['objection', [' to']],
  ['protection', [' against', ' from']],
  ['defense', [' against']],
  ['safeguard', [' against']],
  ['immunity', [' from', ' against', ' to']],
  ['insurance', [' against']],
  ['warning', [' of', ' about']],

  ['plausible', [' that']],
  ['conceivable', [' that']],
  ['inevitable', [' that']],
  ['unavoidable', [' that']],
  ['undeniable', [' that']],
  ['indisputable', [' that']],
  ['regrettable', [' that']],
  ['unfortunate', [' that']],
  ['fortunate', [' that']],
  ['surprising', [' that']],
  ['alarming', [' that']],
  ['encouraging', [' that']],
  ['worrying', [' that']],
  ['ironic', [' that']],
  ['unsurprising', [' that']],
  ['reasonable', [' to', ' that']],
  ['logical', [' to']],
  ['advisable', [' to']],
  ['wise', [' to']],
  ['sensible', [' to']],
  ['unwise', [' to']],
  ['appropriate', [' to', ' for']],
  ['inappropriate', [' for']],
  ['suitable', [' for']],
  ['unsuitable', [' for']],
  ['fit', [' for']],
  ['ready', [' to', ' for']],
  ['willing', [' to']],
  ['unwilling', [' to']],
  ['reluctant', [' to']],
  ['eager', [' to']],
  ['bound', [' to']],
  ['destined', [' to']],
  ['doomed', [' to']],
  ['able', [' to']],
  ['unable', [' to']],

  ['vow', [' to']],
  ['elect', [' to']],
  ['volunteer', [' to']],
  ['offer', [' to']],

  ['the news', [' that']],
  ['the theory', [' that']],
  ['the hypothesis', [' that']],
  ['the premise', [' that']],
  ['the proposition', [' that']],
  ['the understanding', [' that']],
  ['the feeling', [' that']],
  ['the sense', [' that']],
  ['the worry', [' that']],
  ['the fear', [' that']],
  ['the concept', [' of', ' that']],

  // --- Expansion round 6, 2026-06-22: missed high-frequency fixed phrases, obligation adjectives ---
  ['in order', [' to']],
  ['so as', [' to']],
  ['with a view', [' to']],
  ['in an attempt', [' to']],
  ['in an effort', [' to']],
  ['with the goal', [' of']],
  ['with the purpose', [' of']],
  ['hail', [' from']],

  ['forced', [' to']],
  ['compelled', [' to']],
  ['obliged', [' to']],
  ['required', [' to']],
  ['supposed', [' to']],
  ['allowed', [' to']],
  ['permitted', [' to']],
  ['authorized', [' to']],
  ['licensed', [' to']],
  ['apt', [' to']],
  ['disposed', [' to']],
  ['inclined', [' to']],
  ['poised', [' to']],
  ['scheduled', [' to']],
  ['expected', [' to']],

  ['the suspicion', [' that']],
  ['the speculation', [' that']],
  ['the inference', [' that']],
  ['the deduction', [' that']],
  ['the conviction', [' that']],
  ['the verdict', [' that']],
  ['the implication', [' that']],

  // --- Expansion round 7, 2026-06-22: causative/permissive verbs, prevention verbs + "from", more appositives/fixed phrases ---
  ['urge', [' to']],
  ['persuade', [' to']],
  ['encourage', [' to']],
  ['enable', [' to']],
  ['allow', [' to']],
  ['permit', [' to']],
  ['force', [' to']],
  ['compel', [' to']],
  ['oblige', [' to']],
  ['motivate', [' to']],
  ['inspire', [' to']],
  ['prompt', [' to']],
  ['induce', [' to']],
  ['tempt', [' to']],
  ['lure', [' to', ' into']],
  ['drive', [' to']],
  ['push', [' to']],
  ['help', [' to']],

  ['prevent', [' from']],
  ['prohibit', [' from']],
  ['discourage', [' from']],
  ['deter', [' from']],
  ['bar', [' from']],
  ['restrain', [' from']],
  ['shield', [' from']],
  ['protect', [' from', ' against']],
  ['guard', [' against']],
  ['rescue', [' from']],
  ['isolate', [' from']],
  ['segregate', [' from']],
  ['detach', [' from']],
  ['liberate', [' from']],

  ['the demand', [' that']],
  ['the urge', [' to']],
  ['the supposition', [' that']],
  ['the presumption', [' that']],
  ['the stipulation', [' that']],
  ['the insistence', [' that']],
  ['the consensus', [' that']],
  ['the agreement', [' that']],
  ['the stereotype', [' that']],
  ['the myth', [' that']],
  ['the criticism', [' that']],

  ['in the context', [' of']],
  ['in the case', [' of']],
  ['in the process', [' of']],
  ['in the name', [' of']],
  ['on the part', [' of']],
  ['for lack', [' of']],
  ['with reference', [' to']],
  ['in answer', [' to']],
  ['in reply', [' to']],
  ['in opposition', [' to']],
  ['for the duration', [' of']],
  ['at the mercy', [' of']],
  ['on the verge', [' of']],
  ['on the brink', [' of']],
  ['at the core', [' of']],
  ['in the face', [' of']],
  ['for want', [' of']],

  ['the entirety', [' of']],
  ['a string', [' of']],
  ['a litany', [' of']],
  ['a barrage', [' of']],

  // --- Expansion round 8, 2026-06-22: emotion/cognition verbs + "in/at", penalty verbs + "for/of", more appositives/fixed phrases ---
  ['rejoice', [' in', ' at']],
  ['delight', [' in']],
  ['revel', [' in']],
  ['bask', [' in']],
  ['wallow', [' in']],
  ['persist', [' in', ' with']],
  ['excel', [' in', ' at']],
  ['thrive', [' on', ' in']],
  ['dwell', [' on']],
  ['gaze', [' at']],
  ['stare', [' at']],
  ['glance', [' at']],
  ['point', [' to', ' at']],
  ['hint', [' at']],
  ['marvel', [' at']],
  ['laugh', [' at']],
  ['frown', [' at', ' upon']],
  ['look down', [' on', ' upon']],
  ['look up', [' to']],
  ['count', [' on', ' as']],
  ['bank', [' on']],
  ['fend', [' for', ' off']],
  ['budget', [' for']],
  ['arrange', [' for', ' to']],
  ['stand', [' for']],
  ['pay', [' for']],
  ['charge', [' for', ' with']],
  ['forgive', [' for']],
  ['punish', [' for']],
  ['reward', [' for', ' with']],
  ['praise', [' for']],
  ['criticize', [' for']],
  ['condemn', [' for']],
  ['commend', [' for']],
  ['penalize', [' for']],
  ['fine', [' for']],
  ['sentence', [' to', ' for']],
  ['convict', [' of']],
  ['accuse', [' of']],
  ['suspect', [' of']],
  ['cure', [' of']],
  ['relieve', [' of']],
  ['deprive', [' of']],
  ['rob', [' of']],
  ['rid', [' of']],
  ['strip', [' of']],
  ['insure', [' against']],
  ['irrespective', [' of']],

  ['the diagnosis', [' that']],
  ['the testimony', [' that']],
  ['the admission', [' that']],
  ['the confession', [' that']],
  ['the disclosure', [' that']],
  ['the revelation', [' that']],
  ['the acknowledgment', [' that']],
  ['the declaration', [' that']],
  ['the announcement', [' that']],
  ['the assurance', [' that']],
  ['the guarantee', [' that']],
  ['the promise', [' that']],

  ['in the presence', [' of']],
  ['at the discretion', [' of']],
  ['under the guise', [' of']],
  ['under the influence', [' of']],
  ['under the pretext', [' of']],
  ['for the benefit', [' of']],
  ['to the detriment', [' of']],
  ['to the extent', [' that', ' of']],

  ['a slew', [' of']],
  ['a glut', [' of']],
  ['an influx', [' of']],
  ['a torrent', [' of']],

  // --- Expansion round 9, 2026-06-22: manipulation verbs + "into", disagreement verbs + "with", desire nouns + "for", more it-construction adjectives ---
  ['trick', [' into', ' out of']],
  ['deceive', [' into']],
  ['manipulate', [' into']],
  ['coerce', [' into']],
  ['trap', [' into']],
  ['blackmail', [' into']],
  ['bully', [' into']],
  ['scare', [' into']],
  ['frighten', [' into']],
  ['intimidate', [' into']],
  ['cheat', [' out of']],
  ['swindle', [' out of']],

  ['side', [' with']],
  ['team up', [' with']],
  ['quarrel', [' with']],
  ['disagree', [' with']],

  ['flair', [' for']],
  ['knack', [' for']],
  ['talent', [' for']],
  ['gift', [' for']],
  ['penchant', [' for']],
  ['fondness', [' for']],
  ['appetite', [' for']],
  ['craving', [' for']],
  ['thirst', [' for']],
  ['hunger', [' for']],
  ['yearning', [' for']],
  ['longing', [' for']],
  ['zest', [' for']],
  ['enthusiasm', [' for', ' about']],
  ['passion', [' for']],

  ['imperative', [' that', ' to']],
  ['preferable', [' to']],
  ['desirable', [' to', ' that']],
  ['prudent', [' to']],
  ['feasible', [' to']],
  ['practical', [' to']],
  ['impractical', [' to']],
  ['convenient', [' to', ' for']],
  ['inconvenient', [' for']],
  ['worthwhile', [' to']],
  ['pointless', [' to']],
  ['useless', [' to', ' for']],
  ['useful', [' to', ' for']],
  ['helpful', [' to', ' for']],

  ['the dilemma', [' that']],
  ['the paradox', [' that']],
  ['the irony', [' that']],
  ['the catch', [' that']],
  ['the drawback', [' that', ' of']],
  ['the upside', [' of']],
  ['the downside', [' of']],
  ['the flip side', [' of']],

  ['in tandem', [' with']],
  ['in unison', [' with']],
  ['in harmony', [' with']],
  ['in sync', [' with']],
  ['on par', [' with']],
  ['in step', [' with']],
  ['out of line', [' with']],
];
