// Forced single-continuation prefixes for ghost text (issue #6).
//
// Source: STREUSLE corpus (https://github.com/nert-nlp/streusle), commit
// 8ba61fe4f216e7967500a862554a4fff79d25f5d, file `streusle.conllu`.
// License: CC BY-SA 4.0. Generated by scripts/extract_ghost_continuations.py —
// see that file for the extraction method and docs/testing-log.md for the
// domain-fit tradeoff (the corpus is conversational Yelp reviews, not academic
// writing, so coverage is general-English fixed expressions, not IELTS-specific
// collocations).
//
// Each prefix occurs at least twice in the corpus and is followed by the same
// word 100% of the time — not just a frequent n-gram, but cardinality-1 in this
// corpus. Regenerate with: python3 scripts/extract_ghost_continuations.py
export const FORCED_CONTINUATIONS = [
  ['as soon', ' as'],
  ['in front', ' of'],
  ['in the middle', ' of'],
  ['according', ' to'],
  ['in need', ' of'],
  ['when it comes', ' to'],
];
